git: push branch if not on main/master for git-pr
https://github.com/croaky/laptop/pull/276

diff --git a/bin/git-pr b/bin/git-pr
--- a/bin/git-pr
+++ b/bin/git-pr
@@ -2,5 +2,19 @@
 
 set -e
 
+main="master"
+if git branch | grep -Fq "main"; then
+  main="main"
+fi
+
+branch=$(git symbolic-ref --short HEAD)
+
+if [ "$branch" = "$main" ]; then
+  echo "Error: Cannot push from $main branch"
+  echo "Please create a feature branch first"
+  exit 1
+fi
+
+git push
 gh pr create --fill
 gh pr view --web
